#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os, sys

executable = 'mythnimal'

for path, dirs, files in os.walk("."):
   if path.find(".git") == -1:
      for filename in files:
         if filename[-2:] == "py" or filename == executable:
            inlic = True
            wrotelic = False
            firstline = True
            incomment = True
            f = open(path + "/" + filename)
            tempfile = open("/tmp/lictemp", 'w')
            for line in f:
               # Need to skip # lines at the top of the file so we don't blow away the interpreter info
               if line[0] == "#" and line.find("# @") == -1 and incomment:
                  tempfile.write(line)
                  continue
               else:
                  incomment = False
               
               if not wrotelic:
                  licfile = open("licheader")
                  for licline in licfile:
                     tempfile.write(licline)
                  licfile.close()
                  wrotelic = True
               
               if firstline:
                  if line.find("# @Begin License@") == -1:
                     inlic = False
                  firstline = False
               
               if not inlic:
                  tempfile.write(line)
               
               if line.find("# @End License@") != -1:
                  inlic = False

            tempfile.close()
            f.close()
            # For whatever reason this doesn't work
            #os.rename("/tmp/lictemp", "./" + file)
            os.system("mv /tmp/lictemp " + path + "/" + filename)
         